### ISSUE TITLE
Readme says Python 2.7 etc

### ISSUE THREAD

**Issue by francwalter** [TAbdiukov/mwscrape-py3#1]
Hallo

could you update your README.org file?
I guess this is the original forked file, but as I read this forked version is for Python 3.x and not the deprecated 2.7

I ran into problems with the old mwscrape, I wrote it [in the google group](https://groups.google.com/forum/?fromgroups&hl=de#!topic/aarddict/lzjpP0BSQOQ), and should downgrade the CouchDB to 2.x but I think the main problem is more the Python 2.7 so I want to try out your fork.
What do I need to do as install to use your Python 3 version?
Thanks.

frank

EDIT: I found this fork/branch [in the mwscrape repository under PR](https://github.com/itkach/mwscrape/pull/17)

**Comment by francwalter** [comment]
I tried now, installed it (how I think it should be done with Python3):

```
cd /home/franc/aard/
virtualenv env-mwscrape3 -p python3
cd /home/franc/aard/mwscrape3
source bin/activate
pip install git+https://github.com/TAbdiukov/mwscrape-py3
```
which seemed to install errorless:
```
...
Successfully built mwscrape pylru
Installing collected packages: futures, CouchDB, certifi, chardet, idna, urllib3, requests, oauthlib, requests-oauthlib, six, mwclient, pylru, mwscrape
Successfully installed CouchDB-1.2 certifi-2020.4.5.1 chardet-3.0.4 futures-3.1.1 idna-2.9 mwclient-0.10.0 mwscrape-1.1 oauthlib-3.1.0 pylru-1.2.0 requests-2.23.0 requests-oauthlib-1.3.0 six-1.14.0 urllib3-1.25.9

```
but when I try to use it, I immediately run into this error:

```
cd /home/franc/aard/env-mwscrape3
(env-mwscrape3) [15.52.00][root@ew6:/home/franc/aard/env-mwscrape3#mwscrape fr.m.wiktionary.org --speed 5  --db frwiktionary --couch http://admin:12345@127.0.0.1:5984
Traceback (most recent call last):
  File "/home/franc/aard/env-mwscrape3/bin/mwscrape", line 5, in <module>
    from mwscrape import main
ModuleNotFoundError: No module named 'mwscrape'
```
I never had this error in the original mwscrape.
What made I wrong?
Thanks

**Comment by TAbdiukov** [comment]
Let me have a look

**Comment by francwalter** [comment]
> Let me have a look

Did you find something?

**Comment by francwalter** [comment]
It is obsolete now, Igor has updated mwscrape to work with Python 3, and this is working :)
Thank.
